on:
  push:
    branches:
      - develop
  pull_request:
  schedule:
    - cron: '0 0 * * *'

name: Test Script

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        wordpress: ["latest", "trunk", "6.0"]
        install-core-tests: [1, 0]
    runs-on: ubuntu-latest
    name: "Test Script ${{ matrix.wordpress }} - Core Test Suites: ${{ matrix.install-core-tests }}"
    env:
      WP_CORE_DIR: '/tmp/wordpress'
      WP_VERSION: ${{ matrix.wordpress }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Run install-wp-tests.sh"
        shell: bash
        run: |
          export INSTALL_WP_TEST_DEBUG=1
          export WP_INSTALL_CORE_TEST_SUITE=${{ matrix.install-core-tests }}

          bash install-wp-tests.sh wordpress_unit_tests root password 127.0.0.1 "$WP_VERSION" true true true
      - name: "Check Installation"
        shell: bash
        run: bash bin/test-script.sh
